server:
  port: 8888
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示，必须唯一
          uri: lb://user-service # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
             - Path=/user/** # 这个是按照路径匹配，只要以/user/开头就符合要求
#          filters:
#            - AddRequestHeader=Truth,Itcast is freaking awesome!  1
#            - AddRequestHeader=Truth,Itcast is freaking awesome!  2
#            - AddRequestHeader=Truth,Itcast is freaking awesome!  3
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
#      default-filters:
#        - AddRequestHeader=Truth,Itcast is freaking awesome! 1
#        - AXxxHeader=Truth,Itcast is freaking awesome!      2
#        - AXxxHeader=Truth,Itcast is freaking awesome!      3